Repository RFD-FHEM/RFFHEM, pull requests merged in 2018-11, with the labels that each got.

#328 Discart signal received before start sequence before searching pattern for one, zero, float
  .gitattributes
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/lib/signalduino_protocols.hash
  Makefile
  README.md
  controls_signalduino.txt
  test/test_mu_1-definition.txt
  test/test_proto46-definition.txt
Labels: bug

#351 Dev r33 fix lmax mcraw
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test_proto57-definition.txt
Labels: bug

#343 Fix modulematch code for parse_mu sub
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test_modulematch_1-definition.txt
Labels: bug

#299 Firmware Update überarbeiten
  .travis.yml
  CHANGED
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test-runner.sh
  test/test_firmware_download_1-definition.txt
Labels: enhancement

#349 00_SIGNALduino.pm - SIGNALduino_Read()
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug, enhancement

#361 Fixes set flash command for github releaes
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#377 Improve logging and error handling when flashing an arduino
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: enhancement

#383 00_SIGNALduino.pm
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#384 Fixes return value from index function in parse_mu
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
  test/test_mu_1-definition.txt
Labels: bug
