Repository RFD-FHEM/RFFHEM, pull requests merged in 2018-09, with the labels that each got.

#279 updated .travis.yml to prevent automatic merge of pull requests
  .travis.yml
Labels: bug

#273 90_SIGNALduino_un.pm - clean Code + added helpful feature for debug|decode + doc
  CHANGED
  FHEM/90_SIGNALduino_un.pm
Labels: enhancement

#283 00_SIGNALduino.pm - doc sendMSG revised
  CHANGED
  FHEM/00_SIGNALduino.pm
Labels: enhancement

#286 90_SIGNALduino_un.pm
  CHANGED
  FHEM/90_SIGNALduino_un.pm
Labels: bug

#269 14_SD_WS.pm
  CHANGED
  FHEM/14_SD_WS.pm
  FHEM/lib/signalduino_protocols.hash
Labels: SD_WS, enhancement
