Repository RFD-FHEM/RFFHEM, pull requests merged in 2018-12, with the labels that each got.

#403 SD_UT Delete Reading via FHEM API
  FHEM/14_SD_UT.pm
  controls_signalduino.txt
Labels: SD_UT

#402 unittest Module: Fix syntax check to support linebreaks in DEF
  test/98_unittest.pm
Labels: bug

#407 attr 14_SD_UT.pm + hash ID 34 revised
  CHANGED
  FHEM/14_SD_UT.pm
  FHEM/lib/signalduino_protocols.hash
Labels: SD_UT

#409 Add Basic Syntaxcheck Modules via Travis
  Makefile
  test/test_modules-definition.txt
Labels: enhancement

#417 Predeclare FHEMWEB Variables to avoid error
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#418 Automatic check commandef on changed modules
  Makefile
Labels: enhancement

#404 Removed get protocol ids - Added new menu to show protocols and activate/deaktvivate them
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: enhancement

#401 Option in SIGNALduino_callsub to verify sub before running it
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test_callsub_1-definition.txt
Labels: enhancement

#422 patch display Protocol List menu entry
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#424 SD_BELL - update
  CHANGED
  FHEM/14_SD_BELL.pm
Labels: SD_BELL

#444 00_SIGNALduino.pm - SIGNALduino_IdList, neues Verhalten
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
  test/test_developid_1-definition.txt
  test/test_loadprotohash-ok.hash
  test/test_modulematch_1-definition.txt
Labels: bug, enhancement

#459 Update 00_SIGNALduino.pm - fix bug
  FHEM/00_SIGNALduino.pm
Labels: bug

#446 Simple read test in read_overflow Branch einbinden
  Makefile
  test/test-runner.sh
  test/test_read-definition.txt
Labels: unittest

#451 00_SIGNALduino.pm - SIGNALduino_OSV2()
  CHANGED
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test_sub_SIGNALduino_OSV2-definition.txt
Labels: enhancement, oregon

#466 Patch dispatchbin id82
  FHEM/lib/signalduino_protocols.hash
  controls_signalduino.txt
Labels: bug
