Repository RFD-FHEM/RFFHEM, pull requests merged in 2019-02, with the labels that each got.

#434 00_SIGNALduino.pm - Protocollist Overview
  CHANGED
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test_sub_SIGNALduino_getAttrDevelopment-definition.txt
Labels: enhancement

#501 00_SIGNALduino.pm - SIGNALduino_IdList(), bugfix
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#506 Dev r33 hwcheck queryreleases
  CHANGED
  FHEM/00_SIGNALduino.pm
  Makefile
  controls_signalduino.txt
  test/test_firmware_download_1-definition.txt
  test/test_firmware_releases.json
Labels: bug, unittest

#507 Patches error output of unittests
  test/98_unittest.pm
Labels: bug, unittest

#519 Reload protocolHash on demand.
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug, priority

#520 new module for Keeloq devices
  CHANGED
  FHEM/14_SD_Keeloq.pm
  FHEM/90_SIGNALduino_un.pm
  FHEM/lib/signalduino_protocols.hash
  test/test_modules-definition.txt
Labels: enhancement

#524 Some tests for SIGNALduino_Define defaults
  Makefile
  test/test_defineDefaults-definition.txt
Labels: unittest

#523 fix - 14_SD_RSL.pm
  CHANGED
  FHEM/14_SD_RSL.pm
  SD_TOOL/SIGNALduino_TOOL_Dispatch_SD_RSL.txt
Labels: bug

#522 Load Protocolhash from PerlModule instead from textfile
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/lib/signalduino_protocols.hash
  FHEM/lib/signalduino_protocols.pm
  Makefile
  controls_signalduino.txt
  test/test_MS_2-definition.txt
  test/test_defineDefaults-definition.txt
  test/test_developid_1-definition.txt
  test/test_loadprotohash-definition.txt
  test/test_loadprotohash-nok.pm
  test/test_loadprotohash-ok.hash
  test/test_loadprotohash-ok.pm
  test/test_modulematch_1-definition.txt
  test/test_mu_1-definition.txt
Labels: enhancement

#526 00_SIGNALduino.pm
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug
