Repository RFD-FHEM/RFFHEM, pull requests merged in 2019-08, with the labels that each got.

#622 Build Perl if needed to test whith most used versions
  .travis.yml
Labels: bug, priority

#625 00_SIGNALduino.pm - fixed
  CHANGED
  FHEM/00_SIGNALduino.pm
Labels: bug

#627 14_SD_UT.pm - fix
  CHANGED
  FHEM/14_SD_UT.pm
Labels: bug

#628 14_SD_Keeloq.pm - fix
  CHANGED
  FHEM/14_SD_Keeloq.pm
Labels: bug

#630 Fix generation of events for RC_10 ALL + optimizations
  CHANGED
  FHEM/14_SD_UT.pm
  controls_signalduino.txt
Labels: bug, enhancement

#631 SIGNALduino_postDemo_WS2000 - fix Perl warning
  CHANGED
  FHEM/00_SIGNALduino.pm
Labels: bug, fixed

#636 00_SIGNALduino.pm - fix
  CHANGED
  FHEM/00_SIGNALduino.pm
Labels: bug, fixed
