Repository RFD-FHEM/RFFHEM, pull requests merged in 2019-03, with the labels that each got.

#532 Protocol Data / Methods new data model
  FHEM/00_SIGNALduino.pm
  FHEM/lib/SD_PrococolData.pm
  FHEM/lib/SD_Prococols.pm
  Makefile
  controls_signalduino.txt
  test/98_unittest.pm
  test/test_SD_Protocols-definition.txt
  test/test_loadprotohash-nok.pm
  test/test_loadprotohash-ok.pm
Labels: enhancement

#534 Patch filenametypo
  FHEM/00_SIGNALduino.pm
  FHEM/lib/SD_ProtocolData.pm
  FHEM/lib/SD_Protocols.pm
  controls_signalduino.txt
  test/test_SD_Protocols-definition.txt
  test/test_loadprotohash-nok.pm
  test/test_loadprotohash-ok.pm
Labels: bug

#536 Verify SD_WS07 Autocreate via unittest
  Makefile
  test/test_SDWS07-definition.txt
Labels: unittest

#538 Unittest for sub SIGNALduino_read
  test/test_read-definition.txt
Labels: unittest

#531 SD_WS07 fix bug autocreate
  CHANGED
  FHEM/14_SD_WS07.pm
  test/test_SDWS07-definition.txt
Labels: bug

#542 internal versionProtocols fixed
  FHEM/00_SIGNALduino.pm
  FHEM/lib/SD_Protocols.pm
  controls_signalduino.txt
  test/test_defineDefaults-definition.txt
Labels: bug

#543 14_SD_WS07.pm
  CHANGED
  FHEM/14_SD_WS07.pm
  controls_signalduino.txt
Labels: bug

#556 SD_RSL - fix PERL WARNING
  CHANGED
  FHEM/14_SD_RSL.pm
Labels: bug
