Repository RFD-FHEM/RFFHEM, pull requests merged in 2020-12, with the labels that each got.

#907 Master fix - PERL WARNING
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: PERL WARNING

#910 decode and send protocol 56 remote control AC114-01B
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_UT.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: SD_UT, enhancement, fixed

#912 Update 00_SIGNALduino.pm - commandref
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: documentation

#914 90_SIGNALduino_un.pm - PerlCritic / commandref
  CHANGED
  FHEM/90_SIGNALduino_un.pm
  controls_signalduino.txt
Labels: Perl::Critic, documentation

#919 tests-parseMc
  t/FHEM/00_SIGNALduino/01_SIGNALduino_Parse_MC.t
Labels: unittest

#920 Added tests for parse Mx_ subs with corrupt data
  t/FHEM/00_SIGNALduino/01_SIGNALduino_Parse_MN.t
  t/FHEM/00_SIGNALduino/01_SIGNALduino_Parse_MS.t
  t/FHEM/00_SIGNALduino/01_SIGNALduino_Parse_MU.t
Labels: unittest

#923 Fix unittest error in actions and failing SIGNALduino_CheckVersionResp test
  .github/workflows/prove.yml
  CHANGED
  FHEM/00_SIGNALduino.pm
  UnitTest/tests/test_02_sub_SIGNALduino_CheckVersionResp-definition.txt
  controls_signalduino.txt
Labels: bug, unittest
