Repository RFD-FHEM/RFFHEM, pull requests merged in 2021-06, with the labels that each got.

#974 Hideki fix inverted message
  CHANGED
  FHEM/lib/SD_Protocols.pm
  controls_signalduino.txt
  t/SD_Protocols/02_mcBit2Hideki.t
Labels: Hideki, bug

#976 some PerlCritic points - Update 14_SD_WS.pm
  CHANGED
  FHEM/14_SD_WS.pm
  controls_signalduino.txt
Labels: Perl::Critic

#975 Update doc - SD_ProtocolData.pm
  CHANGED
  FHEM/lib/SD_ProtocolData.pm
  controls_signalduino.txt
Labels: documentation

#978 Update README.md
  README.md
Labels: documentation

#941 Fix Multiple Send delay
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
  t/FHEM/00_SIGNALduino/01_SIGNALduino_CheckSendRawResponse.t
Labels: bug

#983 little fix - attr whitelist_IDs
  CHANGED
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#987 little fix - SD_WS - Log3 output
  CHANGED
  FHEM/14_SD_WS.pm
  controls_signalduino.txt
Labels: bug
