Repository RFD-FHEM/RFFHEM, pull requests merged in 2021-12, with the labels that each got.

#1040 wrong syntax in SIGNALduino_Parse_MN
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug, PERL WARNING

#1043 wrong syntax in SIGNALduino_Parse_MU
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#1049 wrong syntax in SIGNALduino_Parse_MS & SIGNALduino_Parse_MC
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: bug

#1050 new protocol definition 7.1 for Mebus HQ7312-2
  FHEM/14_SD_WS07.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: enhancement, SD_WS07
