Repository RFD-FHEM/RFFHEM, pull requests merged in 2021-08, with the labels that each got.

#995 Bresser 5in1 2 - Rename readings windDirection, windDirectionText, windGust and windSpeed
  CHANGED
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  controls_signalduino.txt
  t/FHEM/14_SD_WS/09_parseDatat.t
Labels: SD_WS, enhancement

#999 AVANTEK - Fix
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: SD_BELL, bug

#1001 Fixes Regex, which changes ID Line
  .github/workflows/version.yml
Labels: bug

#1002 new protocol 114 for TR401
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_UT.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: SD_UT

#1007 SIGNALduino_calcRSSI check input parameter
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
  t/FHEM/00_SIGNALduino/02_SIGNALduino_calcRSSI.t
Labels: PERL WARNING

#1008 Fix Warnings cc1101 Unittest
  t/FHEM/cc1101/01_func.t
Labels: unittest, PERL WARNING

#1009 Update protocol 64 for sensor WH2A
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: SD_WS

#1010 new protocol 115 for Bresser 6-in-1 and new 5-in-1 Comfort Wetter Center
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  FHEM/lib/SD_Protocols.pm
  README.md
  controls_signalduino.txt
  t/SD_Protocols/02_ConvBresser_6in1.t
Labels: SD_WS
