Repository RFD-FHEM/RFFHEM, pull requests merged in 2022-02, with the labels that each got.

#1073 Replace version in actions with dynamic value
  .github/workflows/version.yml
  controls_signalduino.txt
Labels: unittest

#1072 new protocol 117 for BRESSER 7-in-1 Weather Center
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  FHEM/lib/SD_Protocols.pm
  README.md
  controls_signalduino.txt
Labels: SD_WS

#1080 14_FLAMINGO.pm - fix attribute room #1079
  FHEM/14_FLAMINGO.pm
  controls_signalduino.txt
Labels: bug
