Repository RFD-FHEM/RFFHEM, pull requests merged in 2022-04, with the labels that each got.

#1085 additional sensors protocol 115 for Bresser 6-in-1 Comfort Wetter Center
  .github/workflows/version.yml
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: enhancement, SD_WS

#1095 Fix wrong calculation of averagewindDirection
  FHEM/14_SD_WS09.pm
  controls_signalduino.txt
  t/FHEM/14_SD_WS09/02_SD_WS09_WindDirAverage.t
  t/FHEM/14_SD_WS09/fhem.cfg
Labels: bug

#1096 Protocol 85 new sensor TFA 30.3251.10
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: SD_WS
