Repository RFD-FHEM/RFFHEM, pull requests merged in 2022-01, with the labels that each got.

#1053 README.md links to outdated thread on forum.fhem.de fixed
  README.md
Labels: documentation

#1055 new protocol 107 for Fine Offset WH51
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
  t/FHEM/00_SIGNALduino/00_SIGNALduino_initialize.t
Labels: enhancement, SD_WS

#1059 Do not check order of rfmodes in test
  t/FHEM/00_SIGNALduino/00_SIGNALduino_initialize.t
Labels: unittest

#1054 Perlcritic Ergebnis bei jedem PR anzeigen
  .github/workflows/perlCritic.yml
  .perlcritic
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
Labels: unittest, Perl::Critic

#1061 new protocol 116 for Fine Offset WH57
  CHANGED
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_WS.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
Labels: SD_WS

#1060 Update 14_SD_UT.pm - fix buttons P90
  FHEM/14_SD_UT.pm
  controls_signalduino.txt
  t/FHEM/14_SD_UT/09_parseDatat.t
  t/FHEM/14_SD_UT/testData.json
Labels: bug, SD_UT

#1066 Graceful load JSON and Digest:CRC Modules
  FHEM/00_SIGNALduino.pm
  FHEM/lib/SD_Protocols.pm
  controls_signalduino.txt
  cpanfile
  t/FHEM/00_SIGNALduino/00_SIGNALduino_initialize.t
  t/FHEM/00_SIGNALduino/01_SIGNALduino_Parse_MN.t
Labels: bug, enhancement

#1071 Update {Match} regex for Hideki Module
  FHEM/14_Hideki.pm
  controls_signalduino.txt
  t/FHEM/14_Hideki/09_ParseData.t
  t/FHEM/14_Hideki/testData.json
Labels: bug, enhancement, Hideki
