Repository RFD-FHEM/RFFHEM, pull requests merged in 2023-01, with the labels that each got.

#1150 Fix usage of frequency when sending
  FHEM/00_SIGNALduino.pm
  controls_signalduino.txt
  t/FHEM/00_SIGNALduino/01_SIGNALduino_Set_sendMsg.t
Labels: bug

#1086 14_Hideki.pm - perlcritic
  FHEM/14_Hideki.pm
  controls_signalduino.txt
  t/FHEM/14_Hideki/09_ParseData.t
Labels: Hideki, Perl::Critic

#1154 Replace round main with round in FHEM::Core::Utils::Math
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_AS.pm
  FHEM/14_SD_WS.pm
  FHEM/14_SD_WS09.pm
  controls_signalduino.txt
Labels: bug, enhancement
