Repository RFD-FHEM/RFFHEM, pull requests merged in 2023-12, with the labels that each got.

#1212 new def | remote ha-hx2
  FHEM/00_SIGNALduino.pm
  FHEM/14_SD_UT.pm
  FHEM/lib/SD_ProtocolData.pm
  README.md
  controls_signalduino.txt
  t/FHEM/14_SD_UT/03_set.t
  t/FHEM/14_SD_UT/fhem.cfg
  t/FHEM/14_SD_UT/testData.json
Labels: enhancement

#1214 Update tests | for the functional reliability of the module SD_UT
  t/FHEM/14_SD_UT/01_define.t
  t/FHEM/14_SD_UT/03_set.t
  t/FHEM/14_SD_UT/fhem.cfg
  t/FHEM/14_SD_UT/testData.json
Labels: unittest, only TEST

#1210 Bump actions/artifact-download and -upload from v3 to v4
  .github/workflows/version.yml
Labels: unittest, dependencies
